INSERT INTO quizzes (user_id, title, public) VALUES (1,'Math Quiz','public');
INSERT INTO quizzes (user_id, title, public) VALUES (1,'Cartoons Quiz','public');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'Fun Trivia Quiz', 'private');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'TV Quiz', 'public');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'Real Housewives Quiz', 'private');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'Dog Quiz', 'public');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'US Politics Quiz', 'public');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'Basic Geography Quiz', 'private');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'Canadian Capitals Quiz', 'public');
INSERT INTO quizzes (user_id, title, public) VALUES (1, 'US Capitals Quiz', 'public');
