-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (1,1, 'Spongebob Squarepants', true);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (2,1, 'Partrick', false);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (3,1, 'Sandy', false);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (4,1, 'Mr. Crabs', false);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (5,2, '3', false);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (6,2, '4', false);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (7,2, '1', false);
-- INSERT INTO answers (id,question_id,answer,is_correct) VALUES (8,2, '2', true);
