INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What is 1 + 1?', 1, '2', '11', 'M', '85',1);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What is 5 x 4?', 1, '30', '8', '20', '25',3);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What is 90 - 30?', 1, '60', '30', '10', '3',1);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Which number is the largest?', 1, '100', '1000', '10000', '10', 3);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What is 7 + 7?', 1, '49', '77', '0', '14', 4);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Who lives in a pineapple under the sea?', 2, 'The Little Mermaid', 'Spongebob Squarepants', 'Moana', 'Sharkie',2);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Who is the Lion King?', 2, 'Nala', 'Simba', 'Sebastien', 'Igor', 2);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Where do the Simpsons live?', 2 'Springfield', 'Los Angeles', 'Pawnee', 'New York', 1);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What cleaning implement comes to life in Fantasia?', 2, 'Mops', 'Brushes', 'Buckets', 'Brooms', 4);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What movie features Anna and Elsa?', 2, 'Encanto', 'Frozen', 'Moana', 'Tangled', 2);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What school are we attending?', 3, 'Bayside High', 'The School of Hard Knocks', 'Lighthouse Labs', 'Code Academy', 3);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Which of these is not a coding language?', 3, 'CoffeeScript', 'JavaScript', 'Java', 'C++', 1);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Which of these is not a shade of blue?', 3, 'Azure', 'Aquamarine', 'Teal', 'Mauve', 4);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('What movie won best picture at the Oscars this year?', 3, 'Elvis', 'Everything Everywhere All at Once', 'All Quiet on the Western Front', 'The Banshees of Inishirin', 2);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('How many points are on the maple leaf on the Canadian flag?', 3, '11', '9', '10', '13', 1);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Who is the star of Ted Lasso?', 4, 'Steve Carell', 'Harrison Ford', 'Will Ferrell', 'Jason Sudeikis', 4);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('How many seasons of The Office were there?', 4, '10', '6', '9', '8', 3);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Who is the host of Survivor?', 4, 'Jeff Probst', 'Alex Trebek', 'Buzz McHenry', 'Bob Foster', 1);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('On what channel or streamer can you watch Succession?', 4, 'Netflix', 'Apple TV +', 'HBO', 'Prime', 3);
INSERT INTO questions (question, quiz_id, answer_1, answer_2, answer_3, answer_4, is_correct) VALUES ('Why is Potomac the best Real Housewives franchise?', 4, 'It just is', 'The Grand Dame', 'It is the funniest', 'All of the above', 4);
