DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  password VARCHAR(255),
);
