DROP TABLE IF EXISTS quizzes CASCADE;

CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  --result_id INTEGER REFERENCES results(id) ON DELETE CASCADE,
  -- question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  public TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
